.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. shitcoin_qt test_shitcoin_qt
clean: FORCE
	$(MAKE) -C .. shitcoin_qt_clean test_shitcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_shitcoin_qt_check
shitcoin-qt shitcoin-qt.exe: FORCE
	 $(MAKE) -C .. shitcoin_qt
